version: '3.9'
services:
  api:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build: ./frontend/image-analyzer-frontend
    ports:
      - "80:80"
    restart: unless-stopped
